import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Web tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <header>
          <h1>Web Tutorial Project</h1>
        </header>
        <nav className="nav">
          <ul>
            <li><Link className="menu-link" href="/Link/1">Link 1</Link></li>
            <li><Link className="menu-link" href="/Link/2">Link 2</Link></li>
            <li><Link className="menu-link" href="/Link/3">Link 3</Link></li>
            <li><Link className="menu-link" href="/Link/4">Link 4</Link></li>
            <li><Link className="menu-link" href="/Link/5">Link 5</Link></li>
          </ul>
        </nav>
        <main>
          <section>
            {children}
          </section>
        </main>
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
