import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Web tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <header>
          <h1>Web Tutorial Project</h1>
        </header>
        <nav>
            <Link href="/Link/1">Link 1</Link>
            <Link href="/Link/2">Link 2</Link>
            <Link href="/Link/3">Link 3</Link>
            <Link href="/Link/4">Link 4</Link>
        </nav>
        <aside>
          <p>aside</p>
        </aside>
        <main>
          <article>
              article
          </article>
          {children}
        </main>
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
